[package]
name = "Barter_Facilitator"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-rustls", "mysql"] }
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "Barter_Facilitator"
path = "Barter_Facilitator.rs"
